deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  on:
    branch: antoine
