- pipeline: CI/CD Elixire
  'on': EVENT
  events:
    - type: PUSH
      refs:
        - refs/heads/main
  priority: NORMAL
  fail_on_prepare_env_warning: true
  actions:
    - action: 'Execute: mix test'
      type: BUILD
      working_directory: /buddy/t-poo-700-timemanager
      docker_image_name: library/elixir
      docker_image_tag: latest
      execute_commands:
        - cd api
        - mix deps.get
      setup_commands:
        - mix local.rebar --force
        - mix local.hex --force
      services:
        - type: POSTGRE_SQL
          version: latest
          connection:
            host: postgres
            port: 5432
            user: postgres
            password: postgres
      volume_mappings:
        - '/:/buddy/t-poo-700-timemanager'
      cache_base_image: true
      shell: BASH
      execute_every_command: true
    - action: 'Execute: npm test'
      type: BUILD
      working_directory: /buddy/t-poo-700-timemanager
      docker_image_name: library/node
      docker_image_tag: '12'
      execute_commands:
        - '# yarn install'
        - cd web
        - npm install
      volume_mappings:
        - '/:/buddy/t-poo-700-timemanager'
      cache_base_image: true
      shell: BASH
    - action: Upload files to 3.17.204.97
      type: SFTP
      input_type: SCM_REPOSITORY
      remote_path: /home/ubuntu/T-POO-700-TimeManager
      login: ubuntu
      password: secure!IN81U0tpDX9m9T8T5N6/tw==.GLA6tdeZcxWNIPbVgSHdQw==
      host: 3.17.204.97
      port: '22'
      authentication_mode: PASS
    - action: '[3.17.204.97] Execute: docker-compose up'
      type: SSH_COMMAND
      working_directory: /home/ubuntu/T-POO-700-TimeManager
      login: ubuntu
      password: secure!IN81U0tpDX9m9T8T5N6/tw==.GLA6tdeZcxWNIPbVgSHdQw==
      host: 3.17.204.97
      port: '22'
      authentication_mode: PASS
      commands:
        - sudo docker-compose build
        - sudo docker-compose up
