version: '3.6'
services:
  adminer:
    image: adminer
    restart: always
    environment:
        ADMINER_DESIGN: mvt
        ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - db
    ports:
      - 8080:8080

  portainer:
    image: portainer/portainer-ce
    volumes:
        - ./portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 9000:9000
  db:
    image: postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE}
        PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
        - '5432:5432'
    networks:
        - db
volumes:
  db:
networks:
  db: